[package]
name = "oauth2"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Florin Lipan <florinlipan@gmail.com>", "David A. Ramos <ramos@cs.stanford.edu>"]
version = "2.0.0-alpha.4"
license = "MIT/Apache-2.0"
description = "Bindings for exchanging OAuth 2 tokens"
repository = "https://github.com/ramosbugs/oauth2-rs"

[dependencies]
base64 = "0.9"
reqwest = { version = "0.9.8", features = [ "trust-dns" ] }
failure = "0.1"
rand = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
sha2 = "0.7"
url = "1.0"

[dev-dependencies]
mockito = "0.8.2"
